sudo: false
language: node_js
node_js:
- '6.1'
cache:
  directories:
  - node_modules
services:
- docker
install:
- npm install
script:
- npm run deploy:dev
- npm run deploy:prod
after_success:
- npm run codecov
- docker login --email=$DOCKER_HUB_EMAIL --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
- export TAG=`if [ "$TRAVIS_TAG" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f Dockerfile -t $DOCKER_IMAGE_NAME .
- if [ ! -z "$TRAVIS_TAG" ]; then docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:$TRAVIS_TAG;
  fi && docker push $DOCKER_IMAGE_NAME
env:
  global:
  - secure: YEsjYMCtmhJuBvr33wsXax9EF2rxOBZJhiRCzx0LKVW8VpXsAWgH2TZoSwm29nhf5DxwwbwMa8AC5KJFstwS75nubfRwEwfetwaz1/2n3j2Jf63qY940k8nDspePXeoN2wK5QYU8Xbb25SA0QQmN70UuCYJR4XaymLQ6k+15Z+XZDpImnBTMbH7BgomRAWy16C/pOPaw+gc1E20WbbdTj2Lhjc6yf+hxCn1K5CBqSMVkJSYVHAAwLog0VTNUhtgKSTgW0+0I25OyJkBmNLhGTd7FUQoLrO27erPCYWIAnu7nCOn6BdN9jczTMGGdJpcEYkXh2CASS1zz28W55KYeta3r59ZW1m/qfvE0rgJZGTU8DNWzy/Z6tgdNNIGmsligufJKipSKZy+kXCfGzRVVXZOjjRKLWSg0xWefrirrM/Pv6tA+io1LDXFGlprf/ZedGBXuEe6MJEBZpv3OwRFbi9ea+t1wY/EObhrKkc5czYXeVxU4qgMsPwY1tzvUBzFzqgkh4aVOOU26nEG1HJUaQhomSGS3ivZQD9b+7NBrCHcHTUk0/FVAsNwilKTGRuxBuEhfm8qS+54Qq/YD6dWEBGrNhyNv/c+mZLx+s6tpv+OSXf+dLfAQZfPJKSrb4WGgmuHnpt0RtTo4txb4aqwNUGJ4KonrIWizd5S1W85EvjQ=
  - secure: jRX3ETcVD9Xv7IBGIncWxi15dTv2U0EokB1apt/PkoTjXol/LloXNt78osyIcsvsiyWkkQVFgg/EVFVUbaqWBNY1Kmx3wEj4oyXfWRFiOdfWomPD/r4mdic1kl4jTvBJHaLUFwnQ1ATa/snoR7nifOw3H0QM/zCJpqPFbFSo5c385UTayHxQjwrE+NkovNpuOVrXSHXzSxJcFB0yzeS1Mo9e8S4EGqfuOGBBdghTuV1Psgx1IExcA3FXFS2px3K/p9IxkYU8fHzme/dRDi9JwXOeKNawGth+zqyGW0Ac93Jub4QrSe9fhKNLlnnkh9mG7zrK61AjrCF5sJ1iKe7eowa+A3RnDzp0n00x5+Mw98u4Hae1rBCy1jg8BKwa1u/O0PICV/HW7w8oKxL3SDN7of9Pgj/y5qcJAC4G1TtPfZ8YVDed4mddXROnE4mDk+SNFR9ma2kEXl/H8YCUjRTo0H4RSE6+Oos99qDpWUVdWhzcNvIeqr04LOfWCPK7ndJ7o2yzJvxM1ldwX1ejlBphq8NHMojS4JaSqU9a3+jUAXgKUHLvEwj2ucn8l42SvTIbsCqR2fnHUMxDWEy6DwvkTTYwciIXasl/y8haOuVB84h3EhljRxkabGmYeWyad+tjDyTuFFg9ai2j0gKOkk5YCnjl4gp2Uhe/q28EiOqdUnQ=
  - secure: DqZbfa5roNCg8embrtHcOCy2fzXrGV1bytmq9pL+i5RJ94zBg9HLr9vDG0j69rWLT7b580yBYQxGOpcuzR/Lz+IX7x48/jEvoehFBYhXhvvMmiwgKkqb7jP1PEL82lRoHP5rwywBGT1yjUtNYVbQHv81ew3xlS5hUptHyG//4aQvQrtPKZfNACN/jBQJ+iwScvKRlyp5guOnxtxG5c2cp2hut08CKnQHneeP81mtJ16UdqwW5yGpnlv+QR/EYgyVNsI9+ABONAl2owNjEVQuwdGC9QhrGfcnMDQ3P6zdplQ2/jGwVcXZ5Avb26GPbRcCdjOzp6yRALaL8gzx/26C9iwuh0OC3iM2Y9pdNqBXsZtZGT49MgPPELfNaOtsUXd4YyFSjodjbCZKtsCbZ28DOUNd1usIyY3T+pdBm/rlcczBm4oggXaajr0Ysp+eOpzDfVrNzrNMqFNkCzGdj9t01zrPm/+3PHXPQKqIk2mwdO0zJK5R7UlGul40x1ZA/GOMMbs3fbEsPpYm0+FUZ1tJPG+f/RVj0+6iGylVRqHkVPiwH8Sc3CxAy87BdRgmWM0qcSuBeCl6e1YwJ/OM07mqU23mMkboWXNpUYfBs627vewzs+MoVytGHXdNVrnZhixrX+ll+s1DISFgqNAiUagJk1hb/WJhrGUIRi8w3XZ//BM=
  - secure: qdYksNXu9or3wZa98tQ48NpZvhlNUr9TL2KKM50o3+Z3jZ+JSk2zy6I2WlE1KN0hHXBWLjRL8lWWVbsisZSSnyzgMfSP7yUNVvJLD4YcxuEkyNb0A9pNmhjihGxq3V/Imb5ZNZII0ScOd/LFfZaI9+tPpg9aOAYjZm3jKhwTKpQifLvJK9Wk/eECqWxaNUFIU9eNsXI6cHZHzVsudCPSnQz22kGe9EsJb/TSdk1KwrZ0r832H9RjUkh5ThCQrL5ETveKoqsuERFRsRicYo0yUBbZ5g9Ig/NvVzwCKlu3+mgYJKw9+y0sEsjveOtsLzIA90VIMoQqTFqBZQqtkQ188n442tkjTZqqQs0B+uhPenyf6VHEpgzldrCWd4Z1k16AAEryOvYbr6rEg1z7gWh7YnJJpzxHkgFeXxaU0TUiPq9sH9olrkrLAByCEKYxSjS7MxbZq6ZLPKMgcnHkzFxrAtfgVzCDkt3KpAy6OiY7ijPw97yULUCsXnIpQONkrIhCIv9JN9l0O4g6nu2M63T0wDSzhVykk4lkh38ZiAzgupOMyo+9QvJNSGgkxfSFzqjtxHoD92Dy7dleM1v+MIo8ft4+dbG5r2Yl+L4xgvFQx1PQ57KFA1uTSbv2CAZwPwji9Hik9Segs7JfFN6xCBdiVqHrS1E2IG6PvmcpkTXwkF0=
